admin_inicio:
    path:     /
    defaults: { _controller: AdminBundle:Inicio:index }

admin_catalogo:
    path:     /catalogo/{id}
    defaults: { _controller: AdminBundle:Catalogo:index, id:0 }

admin_catalogo_categoria_guardar:
    path:     /catalogo/categoria/guardar/
    defaults: { _controller: AdminBundle:Catalogo:guardarCategoria }

admin_catalogo_tabla_guardar:
    path:     /catalogo/tabla/guardar/
    defaults: { _controller: AdminBundle:Catalogo:guardarTabla }

admin_catalogo_tabla_eliminar:
    path:     /catalogo/tabla/eliminar/{id}
    defaults: { _controller: AdminBundle:Catalogo:eliminarTabla, id: 0 }

admin_catalogo_producto_guardar:
    path:     /catalogo/producto/guardar/
    defaults: { _controller: AdminBundle:Catalogo:guardarProducto }

admin_catalogo_categoria_eliminar:
    path:     /catalogo/categoria/eliminar/
    defaults: { _controller: AdminBundle:Catalogo:eliminarCategoria }
    options:
        expose: true

admin_catalogo_producto_editar:
    path:     /catalogo/producto/editar/
    defaults: { _controller: AdminBundle:Catalogo:editarProducto }
    options:
        expose: true

admin_catalogo_producto_cambiarhoja:
    path:     /catalogo/producto/cambiarhoja/
    defaults: { _controller: AdminBundle:Catalogo:cambiarHojaProducto }
    options:
        expose: true

admin_catalogo_producto_eliminar:
    path:     /catalogo/producto/eliminar/{id}/{activo}
    defaults: { _controller: AdminBundle:Catalogo:eliminarProducto }

admin_catalogo_pagina_imprimir:
    path:     /catalogo/pagina/imprimir/{id}
    defaults: { _controller: AdminBundle:Pdf:imprimirPaginaCatalogo, id: 0 }

admin_catalogo_buscar:
    path:     /catalogo/buscarproducto/
    defaults: { _controller: AdminBundle:Catalogo:buscarProducto }
    methods: [GET]