fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

inicio:
  pattern: /
  defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: admin_catalogo
      permanent: true